

syntax = "proto3";
option java_package="com.ritesh.log_aggregation_proto";
option java_outer_classname="LogAggregationProto";
option java_multiple_files=true;

message LogRequest {
  string log_id       = 1;
  string level        = 2;
  string service_name = 3;
  string trace_id = 4;
  string message      = 5;
  string timestamp    = 6;
}
message LogResponse {
  bool   success    = 1;
  string log_id     = 2;
  string message    = 3;
  string error_code = 4;
}
message LogSummary {
  int32  logs_sent = 1;
  int32 logs_kafka  =2;
  int32 logs_db=3;
}

service LogService {


  rpc IngestLog (LogRequest) returns (LogResponse);


  rpc BulkIngest (stream LogRequest) returns (LogSummary);
}

